title: Dominik Downarowicz
description: Dynamics AX / 365 technical consulant
url: https://downardo.at/
author:
  name: Dominik Downarowicz
  twitter: downardo
lang: en_US
branch: main
twitter:
  username: downardo
  card: summary
github_username: downarowiczd
linkedin: dominik-downarowicz

# Pages to include in header navigation
nav_pages:
  - index.html
  - about.md
  - historicSite.md

footer_pages:
  - fine-print.md

# Disqus login information, for comments
disqus:
  shortname: DISQUS_USERNAME

# Links to include on the contact page
contact_links:
  - name: Twitter
    url: https://twitter.com/DOWNARDO
    icon: twitter
  - name: LinkedIn
    url: https://www.linkedin.com/in/dominik-downarowicz/
    icon: linkedin

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      comments: false

plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
  - vendor/bundle/
  - node_modules/
  - js/
  - sass/
  - script/
  - prettier.config.js
  - "*.gem"
  - "*.gemspec"
  - "*.json"
  - "*.ts"

theme: null
permalink: pretty
