title: Dominik Downarowicz
description: Dynamics AX / 365 technical consulant
url: https://downardo.at
author:
  name: Dominik Downarowicz
  twitter: downardo
lang: en-US
branch: main
twitter:
  username: downardo
  card: summary
github_username: downarowiczd
linkedin: dominik-downarowicz

# Pages to include in header navigation
nav_pages:
  - index.html
  - about.md
  - search.html

footer_pages:
  - fine-print.md

# Disqus login information, for comments
disqus:
  shortname: DISQUS_USERNAME

# Links to include on the contact page
contact_links:
  - name: Email
    url: "mailto:dominik@downardo.at"
    icon: fa-solid fa-envelope
  - name: GitHub
    url: https://github.com/downarowiczd
    icon: fa-brands fa-github
  - name: LinkedIn
    url: https://www.linkedin.com/in/dominik-downarowicz/
    icon: fa-brands fa-linkedin

# Front matter defaults
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: post
      comments: true
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: page
      comments: false

plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

exclude:
  - vendor/bundle/
  - node_modules/
  - js/
  - sass/
  - script/
  - prettier.config.js
  - '*.gem'
  - '*.gemspec'
  - '*.json'
  - '*.ts'

include:
  - search.json
  - wiki/

theme: null
permalink: pretty

keep_files: ['wiki']
