#!/bin/sh

set -e

script/build
bundle exec htmlproofer _site \
  --disable-external=true \
  --enforce-https=false \
  --checks=Images,Links,Scripts,OpenGraph \
  --ignore_urls "/apple-touch-icon/,/favicon/,/site.webmanifest/,/wiki/"
bundle exec rubocop -S -D -E
gem build retlab.gemspec
